<a href="https://colab.research.google.com/github/erenonaran/deeplearning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###PyTorch Fundamentals


In [ ]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

### Tensors

Tensors are mainly used data structures in deep learning. Any input data, before going through neural network, gets converted into tensors. The meaning of tensor changes according to the context. In deep learning, it is an object that can represent multi-dimensional data.

Random tensors are used when initializing weights and biases of each neuron in neural network.



In [ ]:
random_tensor = torch.randint(high=10,size=(3,3))
random_tensor1 = random_tensor.reshape(1,3,3)
random_tensor2 = torch.randint(high=10,size=(2,3,3))
print(random_tensor)
print(random_tensor1)
print(random_tensor2)

tensor([[0, 0, 3],
        [5, 3, 3],
        [9, 2, 4]])
tensor([[[0, 0, 3],
         [5, 3, 3],
         [9, 2, 4]]])
tensor([[[2, 4, 4],
         [7, 6, 5],
         [3, 5, 1]],

        [[1, 9, 4],
         [4, 1, 9],
         [3, 6, 3]]])


In [ ]:
print(random_tensor1)
print(random_tensor1.shape)
print(random_tensor1.T.shape)
print(random_tensor1.T)

tensor([[[0, 0, 3],
         [5, 3, 3],
         [9, 2, 4]]])
torch.Size([1, 3, 3])
torch.Size([3, 3, 1])
tensor([[[0],
         [5],
         [9]],

        [[0],
         [3],
         [2]],

        [[3],
         [3],
         [4]]])


<ipython-input-3-d7ea7b3a54f2>:3: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  print(random_tensor1.T.shape)


In [ ]:
print(random_tensor1)
print(random_tensor1.transpose(0,2)) 
print(random_tensor1.T)

tensor([[[0, 0, 3],
         [5, 3, 3],
         [9, 2, 4]]])
tensor([[[0],
         [5],
         [9]],

        [[0],
         [3],
         [2]],

        [[3],
         [3],
         [4]]])
tensor([[[0],
         [5],
         [9]],

        [[0],
         [3],
         [2]],

        [[3],
         [3],
         [4]]])


In [ ]:
print(random_tensor.shape)
print(random_tensor.reshape(1,3,3).shape)
print(random_tensor.shape)

torch.Size([3, 3])
torch.Size([1, 3, 3])
torch.Size([3, 3])


Reshaping/
Viewing/
Stacking/
Squeezing/
Unsqueezing/
Permuting

In [ ]:
rand_tensor = torch.rand(size=(4,4))
print(rand_tensor)
rand_tensor_T = rand_tensor.permute(1,0)
print(rand_tensor_T)
print(rand_tensor_T.is_contiguous())
reshaped_T = rand_tensor_T.reshape(2,8)
print(reshaped_T)
print(reshaped_T.storage().data_ptr() == rand_tensor_T.storage().data_ptr())

tensor([[0.2640, 0.9873, 0.7789, 0.3847],
        [0.0818, 0.2660, 0.2588, 0.8750],
        [0.9074, 0.9556, 0.2796, 0.5298],
        [0.6623, 0.0522, 0.6977, 0.8139]])
tensor([[0.2640, 0.0818, 0.9074, 0.6623],
        [0.9873, 0.2660, 0.9556, 0.0522],
        [0.7789, 0.2588, 0.2796, 0.6977],
        [0.3847, 0.8750, 0.5298, 0.8139]])
False
tensor([[0.2640, 0.0818, 0.9074, 0.6623, 0.9873, 0.2660, 0.9556, 0.0522],
        [0.7789, 0.2588, 0.2796, 0.6977, 0.3847, 0.8750, 0.5298, 0.8139]])
False


In [ ]:
#Indexing
tensor1 = torch.rand(size=(2,4,3))
print(tensor1)
print(tensor1[0,0,1:2])
print(tensor1[0,0,1])

tensor([[[0.6746, 0.1854, 0.8690],
         [0.1117, 0.0139, 0.5740],
         [0.0179, 0.7831, 0.2535],
         [0.2159, 0.0185, 0.4678]],

        [[0.1069, 0.0859, 0.6043],
         [0.5933, 0.5136, 0.4939],
         [0.7223, 0.5720, 0.7961],
         [0.8130, 0.0772, 0.4977]]])
tensor([0.1854])
tensor(0.1854)


In [ ]:
tensor = torch.rand(size=(2,4,3))
indexed_tensor = tensor[:,:,1]
print(tensor)
print(indexed_tensor)
#print(indexed_tensor.storage())
print(tensor.storage().data_ptr())
print(indexed_tensor.storage().data_ptr())
print(indexed_tensor.stride())


tensor([[[0.3997, 0.2946, 0.8405],
         [0.6190, 0.6645, 0.1621],
         [0.1948, 0.1777, 0.9185],
         [0.3412, 0.3112, 0.4292]],

        [[0.9878, 0.3235, 0.5470],
         [0.5169, 0.5240, 0.8919],
         [0.4841, 0.9559, 0.1615],
         [0.3677, 0.0017, 0.5526]]])
tensor([[0.2946, 0.6645, 0.1777, 0.3112],
        [0.3235, 0.5240, 0.9559, 0.0017]])
120945792
120945792
(12, 3)


In [ ]:
import torch
import numpy as pd 

#Default datatype of numpy array is float64, while it is float32 for torch tensor
#Conversions between them keep the dtype same

array = np.arange(start=5.0,stop=11.0)
tensor = torch.from_numpy(array)
print(array)
print(tensor)
array[1] = 15.0
print(array)
print(tensor)


[ 5.  6.  7.  8.  9. 10.]
tensor([ 5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)
[ 5. 15.  7.  8.  9. 10.]
tensor([ 5., 15.,  7.,  8.,  9., 10.], dtype=torch.float64)


In [ ]:
cpu_tensor = torch.tensor([[3,4,5,6],
                           [3,15,2,8]])
gpu_tensor = torch.tensor([[1,2],
                           [3,4]], device="cuda")
print(cpu_tensor.device)
print(gpu_tensor.device)

RuntimeError: ignored

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
#Numpy can work only on CPU

np_array = np.random.rand(3,3)
print(f"np_array:\n{np_array}\n")
tensor_cpu = torch.from_numpy(np_array)
print(f"tensor_cpu:\n{tensor_cpu}\n")
tensor_gpu = tensor_cpu.to(device) #tensor_cpu.cuda() is not used in case GPU is not available
print(f"tensor_gpu:\n{tensor_gpu}\n")
reshaped_tensor_gpu = tensor_gpu.reshape(1,9)
print(f"reshaped_tensor_gpu:\n{reshaped_tensor_gpu}\n")
reshaped_tensor_cpu = reshaped_tensor_gpu.cpu()
print(f"reshaped_tensor_cpu:\n{reshaped_tensor_cpu}\n")
reshaped_array = reshaped_tensor_cpu.numpy()
print(f"reshaped_array:\n{reshaped_array}\n")

np_array:
[[0.92914663 0.26566078 0.84303428]
 [0.47468905 0.25875977 0.06699155]
 [0.60287792 0.8299942  0.5393735 ]]

tensor_cpu:
tensor([[0.9291, 0.2657, 0.8430],
        [0.4747, 0.2588, 0.0670],
        [0.6029, 0.8300, 0.5394]], dtype=torch.float64)

tensor_gpu:
tensor([[0.9291, 0.2657, 0.8430],
        [0.4747, 0.2588, 0.0670],
        [0.6029, 0.8300, 0.5394]], dtype=torch.float64)

reshaped_tensor_gpu:
tensor([[0.9291, 0.2657, 0.8430, 0.4747, 0.2588, 0.0670, 0.6029, 0.8300, 0.5394]],
       dtype=torch.float64)

reshaped_tensor_cpu:
tensor([[0.9291, 0.2657, 0.8430, 0.4747, 0.2588, 0.0670, 0.6029, 0.8300, 0.5394]],
       dtype=torch.float64)

reshaped_array:
[[0.92914663 0.26566078 0.84303428 0.47468905 0.25875977 0.06699155
  0.60287792 0.8299942  0.5393735 ]]

